# Options:
# clean: Remove dead symbolic links that point to the dotfiles directory. Unless
#        the force option is set to true.
# relink: remove existing target but only if it's a symbolic link
# force: remove existing target even if it's a file or directory

- defaults:
    link:
        relink: true

- clean: ['~']

- link:
    ~/.zshrc: zshrc
    ~/.bashrc: bashrc
    ~/.hyper.js: hyper.js
    ~/.vimrc: vim/vimrc
    ~/.config/nvim/init.vim:
        create: true
        path: vim/vimrc
    ~/.tmux.conf: tmux.conf
    ~/.gitconfig: gitconfig
    ~/.ctags: ctags
    ~/.colordiffrc: colordiffrc
    ~/.tldrrc: tldrrc
    ~/.pandoc:
        create: true
        path: pandoc
    ~/.dotfiles: ''

- shell:
    - [curl -L git.io/antigen > antigen.zsh, Installing Antigen]
    - ["git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim", Cloning Vundle for vim]

# TODO:
# - [ ] Link htoprc here
